# Golang CircleCI 2.0 configuration file
version: 2.1
orbs:
    golangci-lint: timakin/golangci-lint@0.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: go build cmd/masl/masl.go
  release:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash

workflows:
  build-lint:
    jobs:
      - golangci-lint/lint
      - build:
          requires:
            - golangci-lint/lint
  release:
    jobs:
      - build:
          filters:
            branches:
              only: master
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
      - release:
          requires:
            - build
          filters:
            branches:
              only: master
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
