# Golang CircleCI 2.0 configuration file
version: 2.1
orbs:
    golangci-lint: timakin/golangci-lint@0.1
jobs:
  release:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash
workflows:
  release:
    jobs:
      - golangci-lint/lint
      - release:
          requires:
            - golangci-lint/lint
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
